"""Research hypothesis, experiment, and experiment results models."""
from datetime import datetime, timezone
from typing import Optional
from sqlalchemy import DateTime, Float, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column
from backend.app.database.base import Base, TimestampMixin


class Hypothesis(Base, TimestampMixin):
    """Trading research hypothesis generated by Research Agent or AI Trading Agent."""
    __tablename__ = "hypotheses"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    hypothesis_id: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)
    strategy_id: Mapped[str] = mapped_column(String(64), default="strategy_v1", nullable=False, index=True)
    title: Mapped[str] = mapped_column(String(256), nullable=False)
    hypothesis_statement: Mapped[str] = mapped_column(Text, nullable=False)
    reasoning: Mapped[str] = mapped_column(Text, nullable=False)
    evidence_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    test_plan: Mapped[Optional[str]] = mapped_column(Text, nullable=True, default="")
    success_metric: Mapped[Optional[str]] = mapped_column(String(256), nullable=True, default="")
    failure_condition: Mapped[Optional[str]] = mapped_column(String(256), nullable=True, default="")
    status: Mapped[str] = mapped_column(String(32), default="PROPOSED", nullable=False)  # PROPOSED, TESTING, VALIDATED, REJECTED


class Experiment(Base, TimestampMixin):
    """Structured experiment record tracking strategy research in Supabase."""
    __tablename__ = "experiments"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    experiment_id: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)  # e.g., EXP-00001
    experiment_name: Mapped[str] = mapped_column(String(128), default="Experiment", nullable=False, index=True)
    strategy_id: Mapped[str] = mapped_column(String(64), default="strategy_v1", nullable=False, index=True)
    baseline_strategy_version: Mapped[str] = mapped_column(String(32), default="v1.0.0", nullable=False)
    candidate_strategy_version: Mapped[str] = mapped_column(String(32), default="v1.1.0", nullable=False)
    hypothesis_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True, index=True)

    # Statuses: CREATED, RUNNING, COMPLETED, FAILED, REJECTED, CANDIDATE, DEMO_VALIDATION, APPROVED
    status: Mapped[str] = mapped_column(String(32), default="CREATED", nullable=False, index=True)

    dataset_description: Mapped[str] = mapped_column(String(256), default="EURUSD_H1", nullable=False)
    training_period: Mapped[Optional[str]] = mapped_column(String(128), nullable=True)
    testing_period: Mapped[Optional[str]] = mapped_column(String(128), nullable=True)
    sample_size: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    created_by: Mapped[str] = mapped_column(String(64), default="TradingResearchAgent", nullable=False)
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Legacy / Compatibility fields
    baseline_strategy: Mapped[str] = mapped_column(String(64), default="strategy_v1", nullable=False)
    candidate_strategy: Mapped[str] = mapped_column(String(64), default="strategy_v1.1", nullable=False)
    strategy_version: Mapped[str] = mapped_column(String(32), default="v1.0.0", nullable=False)
    dataset: Mapped[str] = mapped_column(String(128), default="EURUSD_H1", nullable=False)
    dataset_period: Mapped[str] = mapped_column(String(128), default="90d", nullable=False)
    validation_period: Mapped[Optional[str]] = mapped_column(String(128), nullable=True)
    out_of_sample_period: Mapped[Optional[str]] = mapped_column(String(128), nullable=True)
    parameters_json: Mapped[str] = mapped_column(Text, default="{}", nullable=False)
    metrics_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    robustness_metrics_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    results_summary_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    conclusion: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    action: Mapped[str] = mapped_column(String(128), default="PENDING_HUMAN_REVIEW", nullable=False)
    human_approved: Mapped[bool] = mapped_column(default=False, nullable=False)


class ExperimentResult(Base, TimestampMixin):
    """Immutable evaluation metrics recorded for an experiment."""
    __tablename__ = "experiment_results"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    experiment_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    strategy_version: Mapped[str] = mapped_column(String(32), nullable=False)
    sample_size: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    win_rate: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    profit_factor: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    expectancy: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    net_profit: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    max_drawdown: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    sharpe: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    sortino: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    trade_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    average_trade: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    largest_loss: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    largest_win: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    walk_forward_result_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    monte_carlo_result_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    transaction_cost_assumptions_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    slippage_assumptions_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
